---
kind: pipeline
name: default

steps:
  - name: setup
    image: node:14-alpine
    when:
      event: pull_request
    commands:
      - yarn install

  - name: build
    image: node:14-alpine
    when:
      event: pull_request
    depends_on:
      - setup
    commands:
      - yarn build

  - name: prettier
    image: node:14-alpine
    when:
      event: pull_request
    depends_on:
      - setup
    commands:
      - yarn lint:prettier

  - name: lint
    image: node:14-alpine
    when:
      event: pull_request
    depends_on:
      - setup
    commands:
      - yarn lint
