version: '3.5'
services:
  db:
    image: postgres
    restart: always
    container_name: united_ticket_system
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    env_file:
    - .env
volumes:
  db:
    driver: local
